# allergen-lib.ps1 - the ONE copy of the recipe allergen rule: the vocabulary, the derivation from a
# spec's own ingredients, and the exact bytes of the card's "Contains" line.
# ===================================================================================================
# BRAD'S RULING, 2026-09-12, backlog I144. Every recipe card carries a 'Contains' line naming which of
# the nine major US allergens its ingredients include, derived mechanically from the ingredient map,
# naming the specific nut, shellfish or fish, and explicitly calling out hidden sources such as the
# anchovy in Worcestershire sauce and the shellfish in oyster sauce. The line is GENERATED, never
# hand-written, and a publish check refuses a card whose line is missing or disagrees with its
# ingredients. A short note says it reflects the recipe as written and that readers should check the
# labels of the brands they buy.
#
# WHY THIS IS A READER-SAFETY QUESTION AND NOT A DOCUMENTATION ONE. Measured 2026-09-12 (backlog I144
# rung 1): 42 of 583 recipes contain Worcestershire sauce, which contains anchovy, and the ingredient
# list does not say so; 19 contain oyster sauce. So the otherwise defensible position that a full
# ingredient list is disclosure enough is FALSE for 7.2% of the catalogue. 0 of 584 built cards
# mentioned an allergen at all, while 481 of 583 recipes carry at least one of the top nine.
#
# FORMAT-TcAllergenLine IS THE ONLY PLACE THESE BYTES ARE SPELLED, deliberately. build-card2.ps1
# renders through it and pipeline\audit-allergen-line.ps1 re-derives through it and compares, so
# "disagrees with its ingredients" is a byte comparison against the same function rather than two
# implementations of one rule that drift. This estate has paid for the two-copies shape more than once
# (the price formatter had five copies; the notes-vs-bid check still has two).
#
# THE DERIVATION IS TOTAL OR IT REFUSES. Get-TcRecipeAllergens returns an `unknown` list naming any
# ingredient the table cannot classify, and every caller treats a non-empty `unknown` as a hard stop.
# An unclassified ingredient that quietly contributed nothing would render as "contains nothing" - an
# agreeing zero on a safety line, which is the worst answer available: it looks like a clean lookup.
#
# THE TABLE IS db\allergens.json, generated by pipeline\gen_allergen_table.py, which refuses to write
# unless every row of db\ingredients.json is classified. Its `rule` field states what is listed and
# what deliberately is not (refined oils are exempt; "may contain" is voluntary and never appears).
# ===================================================================================================

# The nine, in the order FALCPA and the FASTER Act name them. Fixed here as well as in the table so a
# truncated or reordered data file cannot silently change what a card claims; Get-TcAllergenTable
# refuses a table whose vocabulary disagrees with this list.
$script:TcAllergenOrder = @('milk','eggs','fish','shellfish','tree_nuts','peanuts','wheat','soy','sesame')
$script:TcAllergenLabel = @{
  'milk'='milk'; 'eggs'='eggs'; 'fish'='fish'; 'shellfish'='shellfish'; 'tree_nuts'='tree nuts'
  'peanuts'='peanuts'; 'wheat'='wheat'; 'soy'='soy'; 'sesame'='sesame'
}
# The note Brad's ruling asks for, in one place. A card that loses it fails the publish check, because
# the check compares the whole line.
$script:TcAllergenNote = 'Generated from the ingredients above, for the nine major US allergens. This is the recipe as written, so read the label on the brands you buy.'

function ConvertTo-TcAllergenHtml {
  # Escapes exactly like build-card2.ps1's Enc2. The specifics and hidden clauses are our own authored
  # data, but "Diced Tomatoes & Green Chilies" proves an ampersand can reach here, and an unescaped one
  # is a broken card rather than a wrong one, which is the kind of defect that ships.
  param([string]$Text)
  if ($null -eq $Text) { return '' }
  return ($Text -replace '&','&amp;' -replace '<','&lt;' -replace '>','&gt;' -replace '"','&quot;' -replace "'",'&#39;')
}

function Get-TcAllergenTable {
  <#
    Reads db\allergens.json into a lookup. Returns @{ Items = <hashtable item -> entry> }.
    THROWS on anything that would make a lookup silently wrong: a missing file, a vocabulary that
    disagrees with $TcAllergenOrder, or two map rows whose names collide case-insensitively (the
    lookup is case-insensitive, so a collision would hand one row's allergens to another's name).
  #>
  param([string]$Path)
  if (-not $Path) { throw 'Get-TcAllergenTable: -Path is required' }
  if (-not (Test-Path -LiteralPath $Path)) { throw ("Get-TcAllergenTable: no allergen table at {0}" -f $Path) }
  $doc = Get-Content -LiteralPath $Path -Raw -Encoding utf8 | ConvertFrom-Json
  $vocab = @($doc.allergens | ForEach-Object { [string]$_.key })
  if (($vocab -join '|') -ne ($script:TcAllergenOrder -join '|')) {
    throw ("Get-TcAllergenTable: the table's vocabulary is '{0}' but the rule is '{1}'" -f ($vocab -join ','), ($script:TcAllergenOrder -join ','))
  }
  $items = @{}
  foreach ($p in $doc.items.PSObject.Properties) {
    if ($items.ContainsKey($p.Name)) {
      throw ("Get-TcAllergenTable: two ingredient names collide case-insensitively on '{0}'" -f $p.Name)
    }
    $contains = @()
    if ($p.Value.PSObject.Properties.Name -contains 'contains') { $contains = @($p.Value.contains | ForEach-Object { [string]$_ }) }
    $hidden = @{}
    if ($p.Value.PSObject.Properties.Name -contains 'hidden' -and $p.Value.hidden) {
      foreach ($h in $p.Value.hidden.PSObject.Properties) { $hidden[[string]$h.Name] = [string]$h.Value }
    }
    $items[$p.Name] = [pscustomobject]@{ contains = $contains; hidden = $hidden }
  }
  return [pscustomobject]@{ Items = $items }
}

function Get-TcRecipeAllergens {
  <#
    THE PREDICATE. Pure: takes the spec's scaler ingredient list and the table's Items hashtable, and
    returns what the card must say. No file access, so every founding case can be pinned without one.

      .present  ordered @( @{ key; label; specifics=@() } ) in the statutory order
      .hidden   ordered @( "<label>, from <clause>" ) deduped, in the statutory order
      .unknown  @( ingredient names the table cannot classify ) - a HARD STOP for every caller

    Keyed on the ingredient's canon name where it has one, exactly as the costing and the vocabulary
    audits key, so a display name that drifts from the map cannot change the answer.
  #>
  param($ScalerIng, $Items)
  $seen = @{}         # key -> hashtable of specifics
  $hiddenBy = @{}     # key -> hashtable of clause -> 1
  $unknown = @()
  foreach ($e in @($ScalerIng)) {
    if (-not $e) { continue }
    $name = if (($e.PSObject.Properties.Name -contains 'canon') -and $e.canon) { [string]$e.canon } else { [string]$e.item }
    if (-not $name) { continue }
    if (-not $Items -or -not $Items.ContainsKey($name)) { $unknown += $name; continue }
    $entry = $Items[$name]
    foreach ($tok in @($entry.contains)) {
      $t = [string]$tok
      if (-not $t) { continue }
      $parts = $t.Split(':', 2)
      $k = $parts[0]
      if (-not $seen.ContainsKey($k)) { $seen[$k] = @{} }
      if ($parts.Count -eq 2 -and $parts[1]) { $seen[$k][$parts[1]] = 1 }
    }
    foreach ($hk in @($entry.hidden.Keys)) {
      if (-not $hiddenBy.ContainsKey($hk)) { $hiddenBy[$hk] = @{} }
      $hiddenBy[$hk][[string]$entry.hidden[$hk]] = 1
    }
  }
  $present = @()
  $hidden = @()
  foreach ($k in $script:TcAllergenOrder) {
    if (-not $seen.ContainsKey($k)) { continue }
    # Sorted so two runs over the same recipe produce the same bytes, whatever order the ingredients
    # happen to sit in. A line that reshuffles between builds would fail its own publish check.
    $specs = @(@($seen[$k].Keys) | Sort-Object)
    $present += [pscustomobject]@{ key = $k; label = $script:TcAllergenLabel[$k]; specifics = $specs }
    if ($hiddenBy.ContainsKey($k)) {
      foreach ($clause in (@($hiddenBy[$k].Keys) | Sort-Object)) {
        $hidden += ("{0}, from {1}" -f $script:TcAllergenLabel[$k], $clause)
      }
    }
  }
  return [pscustomobject]@{ present = @($present); hidden = @($hidden); unknown = @($unknown | Select-Object -Unique) }
}

function Format-TcAllergenLine {
  <#
    THE ONLY SPELLING OF THE LINE. build-card2 renders this; audit-allergen-line re-derives it and
    compares byte for byte. THROWS on an unresolved ingredient rather than rendering a line that
    understates, because on this page understating is exactly as wrong as overstating.
  #>
  param($Result, [string]$Slug = '')
  if (@($Result.unknown).Count -gt 0) {
    throw ("allergen line for '{0}': {1} ingredient(s) are not in db\allergens.json, so the line would understate the recipe: {2}. Classify them in pipeline\gen_allergen_table.py and rerun it." -f $Slug, @($Result.unknown).Count, (@($Result.unknown) -join ', '))
  }
  $names = @()
  foreach ($p in @($Result.present)) {
    $n = ConvertTo-TcAllergenHtml $p.label
    # Brad's ruling: name the SPECIFIC nut or shellfish. A reader allergic to almonds is not served by
    # a bare "tree nuts", and a reader who eats coconut is not served by it either.
    if (@($p.specifics).Count -gt 0) {
      $n += ' (' + ((@($p.specifics) | ForEach-Object { ConvertTo-TcAllergenHtml $_ }) -join ', ') + ')'
    }
    $names += $n
  }
  $contains = if (@($names).Count -gt 0) { ($names -join ', ') + '.' } else { 'none of the nine major US allergens.' }
  $html = '<p class="smp-allergen"><strong>Contains:</strong> ' + $contains
  if (@($Result.hidden).Count -gt 0) {
    $clauses = @($Result.hidden | ForEach-Object { ConvertTo-TcAllergenHtml $_ })
    $html += ' <span class="smp-allergen-hidden">Easy to miss: ' + ($clauses -join '; ') + '.</span>'
  }
  $html += ' <span class="smp-allergen-note">' + (ConvertTo-TcAllergenHtml $script:TcAllergenNote) + '</span></p>'
  return $html
}

function Get-TcCardAllergenLine {
  <#
    Pulls the rendered line back out of a built card body so the publish check can compare it with a
    fresh derivation. Returns $null when the card carries none, which is the "missing" half of the
    refusal Brad's ruling asks for. Non-greedy to the first closing tag, and anchored on the class so
    it cannot pick up some other paragraph.
  #>
  param([string]$Html)
  if (-not $Html) { return $null }
  $m = [regex]::Match($Html, '<p class="smp-allergen">.*?</p>', [Text.RegularExpressions.RegexOptions]::Singleline)
  if (-not $m.Success) { return $null }
  return $m.Value
}
