# build-live-price-script.ps1 - GENERATES public\tc-live-price.js, the live-price fill for every page that is not a
# recipe card (an article, the homepage quote, a tool), FROM the recipe card template (2026-09-22,
# design\RCA-holistic-2026-09-22.md F1; plan grocery\triage-plans\plan-2026-09-22-6.json).
#
# WHY GENERATED. A recipe card fills its placeholders with fillLivePrices() in pipeline\tpl2-scaler-prefix.html.
# Brad's 2026-09-21 ruling put every price on the feed at view time, and the 2026-09-22 ruling C carries that to
# the articles. A hand-written second fill for articles would be the F1 defect in code: two copies of one rule
# that drift apart. So this script cuts the template's OWN functions out verbatim - the feed fetch (SMPFEED,
# smpGetFeed), the feed reader (tcFeedValue) and fillLivePrices itself - and wraps them with the two things a
# page without a card needs: tcStandalone=true (every placeholder is read from the feed) and a start on load.
# A change to the template's fill changes this file on the next run, and -Check fails a checkout where the
# committed file no longer matches its template.
#
# DELIVERY. public\ is the feed Worker's asset directory (wrangler.jsonc), so the file is served at
# https://feed.thriftycrew.com/tc-live-price.js beside smp-feed.json, and a page loads it with one tag:
#   <script src="https://feed.thriftycrew.com/tc-live-price.js" defer></script>
#
# Usage:  build-live-price-script.ps1            write public\tc-live-price.js (LF, no BOM; identical bytes skipped)
#         build-live-price-script.ps1 -Check     exit 1 when the committed file differs from its template
#         build-live-price-script.ps1 -SelfTest
# Exit 0 ok, 1 drift or a failed case, 3 could not evaluate. Last line: LIVE-PRICE-SCRIPT-COMPLETE.
[CmdletBinding()]
param([switch]$Check, [switch]$SelfTest, [string]$Template = '', [string]$OutFile = '')
$ErrorActionPreference = 'Stop'
$here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$repo = Split-Path -Parent (Split-Path -Parent $here)
. (Join-Path $repo 'lib\guard-contract.ps1')
if (-not $Template) { $Template = Join-Path $here 'tpl2-scaler-prefix.html' }
if (-not $OutFile) { $OutFile = Join-Path $repo 'public\tc-live-price.js' }

# One named JS function, brace-matched from its 'function <name>(' to its closing brace. The template's fill
# functions carry no brace inside a string or a regex literal; a cut that does not end on '}' is refused.
function Get-TcJsFunction { param([string]$Src, [string]$Name)
  $i = $Src.IndexOf('function ' + $Name + '(')
  if ($i -lt 0) { throw ("template has no function " + $Name) }
  $open = $Src.IndexOf('{', $i); $depth = 0
  for ($k = $open; $k -lt $Src.Length; $k++) {
    $ch = $Src[$k]
    if ($ch -eq '{') { $depth++ } elseif ($ch -eq '}') { $depth--; if ($depth -eq 0) { return $Src.Substring($i, $k - $i + 1) } }
  }
  throw ("function " + $Name + " never closes")
}

function New-TcLivePriceScript { param([string]$Src)
  $feedVar = [regex]::Match($Src, "var SMPFEED='[^']+'[^;\r\n]*;")
  if (-not $feedVar.Success) { throw 'template has no SMPFEED declaration' }
  $parts = @($feedVar.Value, (Get-TcJsFunction $Src 'smpGetFeed'), (Get-TcJsFunction $Src 'tcFeedValue'), (Get-TcJsFunction $Src 'fillLivePrices'))
  $head = @(
    '/* tc-live-price.js - GENERATED by meal-prep/pipeline/build-live-price-script.ps1 from the recipe card template',
    '   meal-prep/pipeline/tpl2-scaler-prefix.html. DO NOT EDIT: edit the template and regenerate (-Check fails drift).',
    '   Fills every <span data-tc-live-price> on a page that is not a recipe card, from smp-feed.json at view time.',
    '   A value it cannot read (no feed, unknown recipe or commodity, a unit it cannot convert, not a positive number)',
    '   leaves the span''s stamped fallback in place. */',
    '(function(){',
    'if(window.__tcLivePrice) return; window.__tcLivePrice=true;',
    'var tcStandalone=true;',
    'function nServ(){ return 1; }',
    'function totalAt(){ return null; }')
  $tail = @(
    'function go(){ fillLivePrices(); smpGetFeed().then(function(f){ feedData=f; if(!f){ feedFailed=true; } fillLivePrices(); }); }',
    'if(document.readyState===''loading''){ document.addEventListener(''DOMContentLoaded'',go); } else { go(); }',
    '})();')
  return (($head + $parts + $tail) -join "`n") + "`n"
}

if ($SelfTest) {
  $script:fl = 0; $script:n = 0
  function T($m, $c, $g) { $script:n++; if ($c) { Write-Output ('ok    ' + $m) } else { Write-Output ('FAIL  ' + $m + '   got: ' + $g); $script:fl++ } }
  $src = [IO.File]::ReadAllText($Template)
  $js = New-TcLivePriceScript $src
  T 'CLEAN TWIN  the generated script carries the template''s own fillLivePrices, byte for byte' ($js.Contains((Get-TcJsFunction $src 'fillLivePrices'))) ''
  $noFill = $src.Replace('function fillLivePrices(', 'function fillLivePricesGone(')
  $threw = $false; try { New-TcLivePriceScript $noFill | Out-Null } catch { $threw = $true }
  T 'MUST FIRE  a template without fillLivePrices refuses to generate (no hand-written stand-in)' $threw ''
  $committed = if (Test-Path $OutFile) { [IO.File]::ReadAllText($OutFile) } else { '' }
  T 'CLEAN TWIN  the committed public\tc-live-price.js is what the template generates today' ([string]::Equals($committed, $js, [StringComparison]::Ordinal)) ('committed ' + $committed.Length + ' chars, generated ' + $js.Length)
  # RUN IT: the generated script in jsdom over an article-shaped fixture, through the monitor's own harness
  $node = Get-ChildItem 'C:\Codex\tools' -Filter 'node-*-win-x64' -Directory -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
  $jsdom = 'C:\Codex\tools\jsdom-env'
  if ($node -and (Test-Path (Join-Path $jsdom 'node_modules\jsdom'))) {
    $tmp = Join-Path ([IO.Path]::GetTempPath()) ('tc-blps-' + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $tmp -ErrorAction Stop | Out-Null
    try {
      $feed = '{"schema":2,"generated":"2026-09-22T08:14:34","recipes":{"alfredo-fixture":{"everyday_ps":2.51,"per_serving":2.1},"no-key-fixture":{"per_serving":2.1}},"pricing_inputs":{"thighs":{"current":{"unit":"lb","perUnitMicros":1490000},"everyday":{"unit":"lb","perUnitMicros":1990000}},"rice":{"current":{"unit":"oz","perUnitMicros":62500}},"eggs":{"current":{"unit":"each","perUnitMicros":250000}},"odd":{"current":{"unit":"sq_ft","perUnitMicros":1000000}}}}'
      [IO.File]::WriteAllText((Join-Path $tmp 'feed.json'), $feed)
      $body = '<p>A <span data-tc-live-price data-tc-slug="alfredo-fixture" data-tc-field="cost_ps" data-tc-basis="feed-everyday-whole-package" data-tc-fallback="2.40">~$2.40</span> serving.</p>' +
              '<p><span data-tc-live-price data-tc-slug="no-key-fixture" data-tc-field="cost_ps" data-tc-basis="feed-everyday-whole-package" data-tc-fallback="2.85">~$2.85</span></p>' +
              '<p><span data-tc-live-price data-tc-bid="thighs" data-tc-per="lb" data-tc-field="unit_price" data-tc-basis="feed-everyday-per-unit" data-tc-fallback="1.00">~$1.00</span></p>' +
              '<p><span data-tc-live-price data-tc-bid="rice" data-tc-per="lb" data-tc-field="unit_price" data-tc-basis="feed-everyday-per-unit" data-tc-fallback="1.00">~$1.00</span></p>' +
              '<p><span data-tc-live-price data-tc-bid="eggs" data-tc-per="dozen" data-tc-field="unit_price" data-tc-basis="feed-everyday-per-unit" data-tc-fallback="1.00">~$1.00</span></p>' +
              '<p><span data-tc-live-price data-tc-bid="odd" data-tc-per="lb" data-tc-field="unit_price" data-tc-basis="feed-everyday-per-unit" data-tc-fallback="4.44">~$4.44</span></p>' +
              '<script>' + $js + '</script>'
      [IO.File]::WriteAllText((Join-Path $tmp 'a.html'), $body)
      $job = @{ jsdom = $jsdom; feedPath = (Join-Path $tmp 'feed.json'); feedMode = 'ok'; waitMs = 1500; cards = @(@{ slug = 'article-fixture'; htmlPath = (Join-Path $tmp 'a.html'); kind = 'body' }) }
      [IO.File]::WriteAllText((Join-Path $tmp 'job.json'), ($job | ConvertTo-Json -Depth 5))
      $lines = & (Join-Path $node.FullName 'node.exe') (Join-Path $here 'live-price-fill.js') (Join-Path $tmp 'job.json')
      $res = $null; foreach ($l in @($lines)) { if ($l -match '^\{') { $res = $l | ConvertFrom-Json } }
      $sp = @(); if ($res) { $sp = @($res.spans) }
      $txt = ($sp | ForEach-Object { [string]$_.text }) -join ' | '
      T 'CLEAN TWIN  a recipe span on an article fills from feed.recipes[slug].everyday_ps (2.51)' ($sp.Count -eq 6 -and $sp[0].text -eq '~$2.51') $txt
      T 'MUST NOT FIRE  a recipe the feed carries no everyday_ps for keeps its stamped fallback (the landing dependency)' ($sp.Count -eq 6 -and $sp[1].text -eq '~$2.85' -and -not $sp[1].filled) $txt
      T 'CLEAN TWIN  a commodity span reads the EVERYDAY cell over a cheaper sale current (1.99/lb, not 1.49)' ($sp.Count -eq 6 -and $sp[2].text -eq '~$1.99') $txt
      T 'CLEAN TWIN  unit conversion: 0.0625/oz is 1.00/lb, 0.25 each is 3.00/dozen' ($sp.Count -eq 6 -and $sp[3].text -eq '~$1.00' -and $sp[3].filled -and $sp[4].text -eq '~$3.00') $txt
      T 'MUST FIRE  a unit pair the fill cannot convert (sq_ft to lb) is refused and keeps the fallback' ($sp.Count -eq 6 -and $sp[5].text -eq '~$4.44' -and -not $sp[5].filled) $txt
    } finally { Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue }
  } else { Write-Output 'BLIND  node or jsdom missing under C:\Codex\tools: the generated script was not RUN (5 cases not covered)' }
  if ($script:fl -eq 0) { Write-Output ("build-live-price-script self-test PASS ($script:n cases)"); exit 0 } else { Write-Output ("build-live-price-script self-test FAIL ($script:fl of $script:n)"); exit 1 }
}

try { $js = New-TcLivePriceScript ([IO.File]::ReadAllText($Template)) } catch { Write-Output ('COULD NOT GENERATE: ' + $_.Exception.Message); Exit-Guard -Name 'live-price-script' -Summary 'blind=template' -Code 3 }
$cur = if (Test-Path $OutFile) { [IO.File]::ReadAllText($OutFile) } else { '' }
$same = [string]::Equals($cur, $js, [StringComparison]::Ordinal)
if ($Check) {
  if ($same) { Write-Output 'public\tc-live-price.js matches its template' } else { Write-Output 'DRIFT  public\tc-live-price.js differs from what tpl2-scaler-prefix.html generates: run build-live-price-script.ps1 and commit both' }
  Exit-Guard -Name 'live-price-script' -Summary ('drift=' + $(if ($same) { 0 } else { 1 })) -Code $(if ($same) { 0 } else { 1 })
}
if (-not $same) { [IO.File]::WriteAllText($OutFile, $js, (New-Object Text.UTF8Encoding($false))); Write-Output ('wrote ' + $OutFile + ' (' + $js.Length + ' chars)') } else { Write-Output 'unchanged' }
Exit-Guard -Name 'live-price-script' -Summary ('chars=' + $js.Length) -Code 0
