<#
  regenerate-ingredient-map.ps1 - makes meal-prep\ingredient-map.json a DERIVED artifact, generated from
  the 513 spec scaler payloads + the live feed, instead of a hand-authored file frozen at 2026-07-07.

  WHY (2026-07-26 Fable re-review): the frozen map was missing 58 ingredients the current catalog uses
  (its consumers - dinner tool, protein leaderboard, top5 sale badges, normalize-recipe-ids - silently
  could not price them), and it disagreed with the specs on 48 more. The specs are the vetted source:
  their gpu values were unit-reconciled against the feed on all live cards 2026-07-25 (the 16x lesson),
  and they are what the live card widgets actually price with.

  POLICY (explicit, deterministic):
   - For each distinct scaler item name across db\recipes\*.json, collect every (bid,gpu) variant with
     its usage count.
   - Choose the HIGHEST-COUNT variant whose bid RESOLVES on the live feed. Majority-rule means the map
     (and therefore the tools) agree with what MOST live cards show today. It does NOT adjudicate which
     product is "right" for the 50 items where spec eras disagree - that is the spec-side reconciliation
     project (see db\worklists\bid-conflicts-*.md), and this script will pick up its results automatically
     the day the specs converge, because it derives from them.
   - unit comes from the FEED row (guarantees build-protein-data's unit-equality guard passes).
   - board = 'recipe' when the bid is on grocery\out\recipe-board.json, else 'weekly' (top5's delta pass
     uses only board='recipe' rows, matching the old map's semantics).
   - Items whose every variant is off-feed are skipped and reported (the exotic no-board-price class).

  Output keeps the EXACT consumed shape: { mappings:[{item,board_id,board,grams_per_unit,unit}] }.
  Conflicted items are listed in the output's `conflicts` block for visibility.
  Run after any recipe batch lands (wired next to compute-v2 in the daily chain).
#>
param([string]$OutPath = '')
$ErrorActionPreference = 'Stop'
. (Join-Path (Split-Path $PSScriptRoot -Parent) 'lib\json-io.ps1')   # Read-JsonFile: PS 5.1 decodes a BOM-less file with the ANSI codepage
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$mp = Split-Path -Parent $here
$repo = Split-Path -Parent $mp
if (-not $OutPath) { $OutPath = Join-Path $mp 'ingredient-map.json' }

$feed = (Get-Content (Join-Path $repo 'grocery\out\smp-feed.json') -Raw -Encoding utf8 | ConvertFrom-Json).ingredients
$fk = @{}; foreach ($p in $feed.PSObject.Properties) { $fk[$p.Name] = $p.Value }
$recipeBoardIds = @{}
try { foreach ($r in (Read-JsonFile (Join-Path $repo 'grocery\out\recipe-board.json')).comparison) { $recipeBoardIds[[string]$r.id] = 1 } } catch {}

# collect variants per item across all specs
$byItem = @{}
foreach ($sf in (Get-ChildItem (Join-Path $mp 'db\recipes\*.json'))) {
  $s = Read-JsonFile $sf.FullName
  foreach ($ing in $s.scaler.ing) {
    $it = [string]$ing.item
    $b = if ($ing.PSObject.Properties.Name -contains 'bid') { [string]$ing.bid } else { '' }
    if (-not $b) { continue }
    $g = if ($ing.PSObject.Properties.Name -contains 'gpu' -and $ing.gpu) { [math]::Round([double]$ing.gpu, 4) } else { 0 }
    if ($g -le 0) { continue }
    if (-not $byItem.ContainsKey($it)) { $byItem[$it] = @{} }
    $key = "$b|$g"
    if (-not $byItem[$it].ContainsKey($key)) { $byItem[$it][$key] = 0 }
    $byItem[$it][$key]++
  }
}

$mappings = New-Object System.Collections.Generic.List[object]
$conflicts = New-Object System.Collections.Generic.List[object]
$skipped = New-Object System.Collections.Generic.List[string]
foreach ($it in ($byItem.Keys | Sort-Object)) {
  $variants = @($byItem[$it].GetEnumerator() | Sort-Object -Property @{e={-$_.Value}}, @{e={$_.Key}})
  $chosen = $null
  foreach ($v in $variants) {
    $b = ($v.Key -split '\|')[0]
    if ($fk.ContainsKey($b)) { $chosen = $v; break }   # highest-count FEED-RESOLVING variant wins
  }
  if (-not $chosen) { $skipped.Add($it); continue }
  $bid = ($chosen.Key -split '\|')[0]
  $gpu = [double](($chosen.Key -split '\|')[1])
  $board = if ($recipeBoardIds.ContainsKey($bid)) { 'recipe' } else { 'weekly' }
  $mappings.Add([ordered]@{ item = $it; board_id = $bid; board = $board; grams_per_unit = $gpu; unit = [string]$fk[$bid].unit })
  if ($variants.Count -gt 1) {
    $conflicts.Add([ordered]@{ item = $it; chosen = $chosen.Key; all = @($variants | ForEach-Object { "$($_.Key) x$($_.Value)" }) })
  }
}

$doc = [ordered]@{
  readme = 'DERIVED FILE - regenerated by pipeline\regenerate-ingredient-map.ps1 from the db\recipes spec scaler payloads + the live feed. Do NOT hand-edit; fix the specs (or the feed) and re-run. Maps recipe ingredient item names to feed/board commodity ids; grams_per_unit converts grams into the feed row''s pricing unit; unit always matches the feed row. conflicts lists items whose specs disagree across eras (majority-feed-resolving wins here; the spec-side reconciliation worklist is db\worklists\bid-conflicts-2026-07-26.md).'
  generated_at = (Get-Date).ToString('s')
  mappings = $mappings.ToArray()
  conflicts = $conflicts.ToArray()
}
$json = $doc | ConvertTo-Json -Depth 6
[IO.File]::WriteAllText($OutPath, $json, (New-Object System.Text.UTF8Encoding($false)))
$null = Read-JsonFile $OutPath
Write-Output ("ingredient-map.json REGENERATED: {0} mappings ({1} had cross-spec conflicts, majority-feed rule), {2} skipped off-feed: {3}" -f $mappings.Count, $conflicts.Count, $skipped.Count, (($skipped | Select-Object -First 6) -join ', '))
