export interface JournalQueueJob {
  id: string; directory: string; sourceId: string; status: string; enqueuedAt: string; nextAttemptAt: string; manifestJson: string;
}
export function captureJournalPath(environment?: NodeJS.ProcessEnv): string;
export function upsertQueueJournalJob(job: JournalQueueJob, file?: string): void;
export function queueJournalJobs(file?: string): JournalQueueJob[];
export function acquireQueueJournalLease(jobId: string, owner: string, now: Date, leaseMs?: number, file?: string): boolean;
export function releaseQueueJournalLease(jobId: string, owner: string, file?: string): void;
export function upsertSessionJournal(directory: string, draft: { sessionId: string; store: string; chunks?: Array<{ id: string; file: string; sha256: string; createdAt: string }> }, file?: string): void;
export function readSessionJournal<T>(directory: string, file?: string): T | null;
export function commitSessionChunk(directory: string, draft: { sessionId: string; store: string; chunks: Array<{ id: string; file: string; sha256: string; createdAt: string }> }, entry: { id: string; file: string; sha256: string; createdAt: string }, body: Uint8Array, file?: string): void;
export function readSessionPayload(directory: string, payloadId: string, file?: string): { file: string; sha256: string; contentType: string; body: Uint8Array; kind: string; createdAt: string } | null;
export function storeSessionEvidence(directory: string, input: { id: string; kind: string; file: string; sha256: string; contentType: string; body: Uint8Array; createdAt: string }, file?: string): void;
export function sessionEvidence(directory: string, file?: string): Array<{ id: string; kind: string; file: string; sha256: string; contentType: string; byteLength: number; createdAt: string }>;
export function replaceSessionWorkUnits(directory: string, store: string, phase: string, units: Array<{ key: string; ordinal: number; priority?: number; payload?: Record<string, unknown> }>, observedAt?: string, file?: string): void;
export function completeSessionWorkUnits(directory: string, phase: string, unitKeys: string[], resultChunkId?: string, file?: string): void;
export function leaseCaptureWork(owner: string, requestedStore?: string, now?: Date, ttlMs?: number, file?: string): Record<string, unknown>;
export function heartbeatCaptureWork(owner: string, workId: string, now?: Date, ttlMs?: number, metadata?: Record<string, unknown>, file?: string): Record<string, unknown>;
export function failCaptureWork(owner: string, workId: string, error: string, retryAt?: Date, file?: string): void;
export function openCaptureChallenge(store: string, detail?: Record<string, unknown>, now?: Date, file?: string): { id: string; idempotent: boolean };
export function acknowledgeCaptureChallenge(id: string, now?: Date, file?: string): Record<string, unknown>;
export function resolveCaptureChallenge(id: string, canaryPassed: boolean, now?: Date, file?: string): Record<string, unknown>;
export function recordStoreRateResult(store: string, outcome: string, latencyMs: number, now?: Date, file?: string): Record<string, unknown>;
export function captureCoordinatorStatus(file?: string): Record<string, unknown>;
export function setCaptureSessionPhase(sessionId: string, phase: string, observedAt?: string, file?: string): Record<string, unknown>;
export function browserCaptureJournalDueState(now?: Date, file?: string): Record<string, unknown> | null;
export function readPlannerJournal(namespace: string, file?: string): Record<string, Record<string, unknown>>;
export function replacePlannerJournal(namespace: string, values: Record<string, Record<string, unknown>>, observedAt: string, file?: string): void;
export function serializeCaptureJournal(file?: string): Uint8Array;
export function closeCaptureJournals(): void;
export function acquireControllerLane(store: string, owner: string, now?: Date, ttlMs?: number, environment?: NodeJS.ProcessEnv): { acquired: boolean; active?: number; reason?: string };
export function releaseLaneLease(store: string, owner: string, environment?: NodeJS.ProcessEnv): void;
export function writeLaneState(store: string, state: Record<string, unknown>, environment?: NodeJS.ProcessEnv): void;
